### ISSUE TITLE
Bomb Balls sometimes not stunning player

### ISSUE THREAD

**Issue by Flave229** [Mike430/TGP_Second_Semester#1]
**Description:**
When a grey bomb ball falls out of the ball dispenser and the player hits it, the bomb successfully blows up but occasionally does not stun the player as intended. This has only occurred on the left player in testing, and is likely the result of hitting the bomb straight after another action.

**To replicate:** 
Keep getting the left player to hit bomb balls immediately after hitting another ball and eventually the bug should occur.

**Occurance:**
Occurs 30% of the time, provided the replication instructions are followed.

**Device:** 
Android, Nexus 5

**Image:**
![image](http://i.imgur.com/AY0L5gX.gifm)

**Comment by Mike430** [comment]
This is likely due to the fact that there are invincibility power ups and when stunned you cannot take damage for a limited period of time, it's so you can't stun lock opponents. We'll work on making passive effects and power ups more immediately understandable.
