### ISSUE TITLE
Game will crash when attempting to boot up on a mobile phone

### ISSUE THREAD

**Issue by Malcom-Nubbins** [Mike430/TGP_Second_Semester#5]
**Issue:**
When attempting to launch the game on my phone, it will completely crash, and will fail to open at all. It will only crash on my phone, however, and not my tablet. Which leads me to believe it is due to the version of Android my phone is running (KitKat 4.4.4, compared to my tablet which is running Marshmallow 6.0.1).

**Possible Cause:**
Its possible that its due to the Android SDK version that is being used with Cocos2d-x 3.9.

**Occurrence rate:**
100% on my phone, 0% on any other of my devices.

**Device:**
Google Nexus 5 (Android Version 4.4.4, KitKat).

![screenshot_2016-04-08-09-45-51](https://cloud.githubusercontent.com/assets/7977281/14380540/e6d62296-fd77-11e5-91bb-45188386fb06.png)

**Comment by BartoszGrabowski** [comment]
Android 4.4 is not supported
