### ISSUE TITLE
Crashes on Android [Gameplay]

### ISSUE THREAD

**Issue by Gingernut151** [Mike430/TGP_Second_Semester#8]
**Reproduce:** Press the main game button on the menu screen
**Consequence:** The game crashed
**Expected:** To play the main game
**Device:** Samsung Galaxy Note 3 (KitKat 4.4)

![image](https://cloud.githubusercontent.com/assets/9529895/14572747/6f781e08-0348-11e6-8cc6-7b7e8748d748.png)

**Comment by BartoszGrabowski** [comment]
android 4.4 is not supported
